import { Inter } from "next/font/google";
import "./globals.css";
import { BotConnector } from "@/components/bot";
import { UserConnector } from "@/components/Connectors";
import clsx from "clsx";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://telegram.org/js/telegram-web-app.js"></script>
      </head>
      <body className={clsx(inter.className)}>
        <BotConnector />
        <div className="flex flex-col items-center w-full h-screen">
          {children}
          <UserConnector />
        </div>

        <Toaster />
      </body>
    </html>
  );
}
